
name: Windows

on:
  push:
    branches: [ "main" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      SDL2_VERSION: 2.28.5

    steps:
    - uses: actions/checkout@v3

    - name: Download SDL2
      run: |
        Invoke-WebRequest -Uri "https://github.com/libsdl-org/SDL/releases/download/release-$env:SDL2_VERSION/SDL2-devel-$env:SDL2_VERSION-VC.zip" -OutFile "SDL2-devel-$env:SDL2_VERSION-VC.zip"
        Expand-Archive -Path "SDL2-devel-$env:SDL2_VERSION-VC.zip" -DestinationPath .

    - name: Build
      run: |
        cmake -B build -A x64 -DSDL2_ROOT="SDL2-$env:SDL2_VERSION"
        cmake --build build --config Release

    - uses: actions/upload-artifact@v3
      with:
        name: snakespasm-win64
        path: build/Release/snakespasm.exe

